- set_fact:
   nodejs: {}

- name: check nodenv
  command: |
    bash -lc 'which nodenv'
  register: which_nodenv
  ignore_errors: yes

- name: install nodenv
  command: |
    bash -lc 'anyenv install nodenv'
  when: which_nodenv.rc > 0

- name: get install versions
  command: |
    bash -lc 'nodenv versions'
  register: installed_versions
  ignore_errors: yes

- name: install nodejs
  command: |
    bash -lc 'nodenv install {{ item | quote }}'
  when: |
    nodejs.versions and installed_versions.stdout.find(item) == -1
  with_items: '{{ nodejs.versions }}'

- name: set global nodejs
  command: |
    bash -lc 'nodenv global {{ nodejs.versions[0] | quote }}'
  when: nodejs.versions

- name: rehash
  shell: |
    if [ -f "$DOTSHIM_FILE" ]; then
      rm -f "$DOTSHIM_FILE"
    fi
    bash -lc 'nodenv rehash'
  environment:
    DOTSHIM_FILE: '{{ anyenv.envs_dir }}/nodenv/.nodenv-shim'
