- name:       kouki development environment
  hosts:      127.0.0.1
  connection: local

  vars:
    home_path:     '{{ lookup("env", "HOME") }}'
    dotfiles_path: '{{ home_path }}/dotfiles'

  environment:
    PATH: '/usr/local/bin:{{ anyenv.envs_dir }}/rbenv/shims:{{ anyenv.envs_dir }}/ndenv/shims:{{ anyenv.envs_dir }}/pyenv/shims:{{ anyenv.envs_dir }}/goenv/shims:{{ lookup("env", "PATH") }}'

  roles:
    #  basic
    #-----------------------------------------------

    # install 
    #-----------------------------------------------
    - role: homebrew
      tags: ['install', 'homebrew']

    # lang
    #-----------------------------------------------