- name:       kouki development environment
  hosts:      127.0.0.1
  connection: local

  vars:
    home_path:     '{{ lookup("env", "HOME") }}'
    dotfiles_path: '{{ home_path }}/dotfiles'

  roles:
    #  basic
    #-----------------------------------------------
    - role: link
      tags: ['basic', 'link']

    # install 
    #-----------------------------------------------
    - role: homebrew
      tags: ['install', 'homebrew']
    - role: mas
      tags: ['install', 'mas']

    # lang
    #-----------------------------------------------